// Generates supabase/seed.sql from src/data/exercises.ts (the single source of truth).
// Run with:  npm run seed:gen
// (Node 24 can read .ts files directly, so no extra tools are needed.)
import { writeFileSync } from "node:fs";
import { EXERCISES } from "../src/data/exercises.ts";

const q = (s) => `'${String(s).replaceAll("'", "''")}'`; // SQL string
const arr = (a) => (a.length ? `array[${a.map(q).join(",")}]::text[]` : "'{}'::text[]");

const rows = EXERCISES.map(
  (e) =>
    `  (${q(e.id)}, ${q(e.name)}, ${q(e.muscleGroup)}, ${arr(e.equipment)}, ${e.difficulty}, ${e.durationMin}, ${e.benefit}, ${q(e.impact)}, ${arr(e.tags)}, ${q(e.unit)}, ${arr(e.easierIds)}, ${q(e.howTo)})`,
);

const sql = `-- GENERATED by scripts/gen-seed.mjs from src/data/exercises.ts. Do not edit by hand.
-- Run in Supabase → SQL Editor after schema.sql. Safe to run again (it updates existing rows).
insert into public.exercises
  (id, name, muscle_group, equipment, difficulty, duration_min, benefit, impact, tags, unit, easier_ids, how_to)
values
${rows.join(",\n")}
on conflict (id) do update set
  name = excluded.name, muscle_group = excluded.muscle_group, equipment = excluded.equipment,
  difficulty = excluded.difficulty, duration_min = excluded.duration_min, benefit = excluded.benefit,
  impact = excluded.impact, tags = excluded.tags, unit = excluded.unit,
  easier_ids = excluded.easier_ids, how_to = excluded.how_to;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql with ${EXERCISES.length} exercises.`);
